version: "3.3"
services:
  logstash:
    build: ./logstash
    volumes:
      - "./logstash/logstash.yml:/workspace/logstash-7.6.0/config/logstash.yml"
    ports:
      - "5054:5054"
      - "5051:5051"
  redis:
    build: .
    ports:
      - 6379:6379
  elk:
    image: sebp/elk
    volumes:
      - "./02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf"
      - "./30-output.conf:/etc/logstash/conf.d/30-output.conf"
      - "./elasticsearch:/var/log/elasticsearch"
    environment:
      - ES_HEAP_SIZE=3g
      - MAX_MAP_COUNT=262144
      - ELASTICSEARCH_START=1
      - LOGSTASH_START=1
      - KIBANA_START=1
      - ES_CONNECT_RETRY=500
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "4718:4718"
