version: "3.3"
services:
  redis:
    build: .
    ports:
      - 6379:6379
  elk:
    image: sebp/elk
    volumes:
      - "./02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf"
    environment:
      - ES_HEAP_SIZE=2g
      - MAX_MAP_COUNT=262144
      - ELASTICSEARCH_START=1
      - LOGSTASH_START=1
      - KIBANA_START=1
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "4718:4718"
